# Generated by Django 3.2.6 on 2021-08-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(default='', max_length=255)),
                ('Lname', models.CharField(default='', max_length=255)),
                ('Email', models.EmailField(default='', max_length=255)),
                ('mobile', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
