# Generated by Django 3.2.6 on 2021-08-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='sendstatus',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
