# Generated by Django 3.2.6 on 2021-09-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emailrecord_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailrecord',
            name='check',
        ),
    ]
