# Generated by Django 3.2.6 on 2021-09-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_emailrecord_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='sendstatus',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
