# Generated by Django 3.2.6 on 2021-09-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_emailrecord_sendstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='sendstatus',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
