# Generated by Django 3.2.6 on 2021-09-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_emailrecord_sendstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default='', max_length=255)),
                ('lname', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('password', models.TextField(default='', max_length=500)),
                ('mobile', models.CharField(default='', max_length=20)),
                ('profile', models.ImageField(default='users/dummy.jpg', upload_to='users/')),
            ],
        ),
    ]
