# Generated by Django 3.2.6 on 2021-09-11 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usersignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReferalRecord',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('userClickId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userclick', to='api.usersignup')),
                ('userReferenceId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userreferece', to='api.usersignup')),
            ],
        ),
    ]
