# Generated by Django 3.2.6 on 2021-09-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_discountprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreferalrecord',
            name='discountprice',
            field=models.IntegerField(default=0),
        ),
    ]
