# Generated by Django 3.2.6 on 2021-09-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userreferalrecord_discountprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='account_Status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=10),
        ),
    ]
