# Generated by Django 3.2.6 on 2021-09-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_usersignup_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountprice',
            name='discountlink',
            field=models.TextField(default=''),
        ),
    ]
