# Generated by Django 3.2.6 on 2021-10-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210924_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='totalnoofappointment',
            field=models.IntegerField(default=0),
        ),
    ]
