# Generated by Django 3.2.6 on 2022-01-26 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_usersignup_totalnoofappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreferalrecord',
            name='userClickId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userclick', to='api.usersignup'),
        ),
        migrations.AlterField(
            model_name='userreferalrecord',
            name='userReferenceId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userreferece', to='api.usersignup'),
        ),
    ]
