# Generated by Django 3.2.6 on 2022-02-11 09:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220126_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='landingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
