# Generated by Django 3.2.6 on 2022-02-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_landingcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailReferalrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('first', 'first'), ('second', 'second'), ('third', 'third')], default='first', max_length=10)),
                ('userRecieve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieve', to='api.usersignup')),
                ('userReference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refer', to='api.usersignup')),
            ],
        ),
    ]
