# Generated by Django 3.2.6 on 2022-02-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220212_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreferalrecord',
            name='userRecieve',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
