# Generated by Django 3.2.6 on 2022-02-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_emailreferalrecord_userrecieve'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailreferalrecord',
            name='recieverFirstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailreferalrecord',
            name='creation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
