# Generated by Django 3.2.6 on 2022-02-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20220212_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailreferalrecord',
            name='referFirstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailreferalrecord',
            name='userReference',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
