# Generated by Django 3.2.6 on 2022-03-10 07:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20220212_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='referalCompaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
