# Generated by Django 3.2.6 on 2022-03-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_referalcompaign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='referalCompaign',
            new_name='referalTemplate',
        ),
    ]
