# Generated by Django 3.2.6 on 2022-03-10 10:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_referalcompaign_referaltemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='friendRefTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
