# Generated by Django 3.2.6 on 2022-03-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_friendreftemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='smsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
